### ISSUE TITLE
[PE-D] No indication on the baseline for labelling FET as late.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-T15-4/tp#201]
When using the app, I noticed that 22 Oct 2021 is the benchmark to determine whether FET is late.
It is not clear (or not obvious) in the UG that perhaps the previous Friday is the benchmark? 

More information needs to be given to make this clear to users.

-------------
Labels: `type.DocumentationBug` `severity.High`
original: eeliana/ped#16

**Comment by gordonlzy** [comment]
I think this issue is here because the tester was not aware of the one week validity period of last fet, maybe can include it in the doc

**Comment by VimuthM** [comment]
Yes, please do
