### ISSUE TITLE
[PE-D] Missing find command for events in UG

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-T15-4/tp#213]
There is a find command for events in the Command Summary of the UG and it works in the application but is not reflected in the UG with description, examples and format.

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: nguyiyang/ped#7

**Comment by chongjunwei** [comment]
Duplicate, #219 contains the same issue along with other missing commands
